name: 'Nightly Release'

on:
  workflow_run:
    workflows: ['Build / Lint']
    branches:
      - master
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run build
        run: npm run build:chrome

      - name: Package extensions
        run: |
          cd dist-chrome
          zip -r -FS ../favrec-ext.chrome.zip *

      - name: Release Chrome
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/smallkirby/favrec-ext/releases/133279364/assets{?name,label}
          asset_path: ./favrec-ext.chrome.zip
          asset_name: favrec-ext.chrome.zip
          release_id: 133279364
          asset_content_type: application/zip
          max_releases: 1
